### ISSUE TITLE
ピクセルの色の付き方

### ISSUE THREAD

**Issue by Sabazo** [a-know/Pixela#9]
ピクセルの色のグラデーション仕様がわからないのですが、整数モードで、
0,1,2,3の1刻みのときと、0,10,20,30の10刻みのときの色の付き方が
異なるのは仕様でしょうか?
(小さい数値のときはグラデーション表示は諦めるしかない?)

https://pixe.la/v1/users/sabazo/graphs/testpi.html
0,1,2,3 → 2019/5/19～
0,10,20,30 → 2018/1/16～

**Comment by a-know** [comment]
Thank you for feedback!
I will confirm later.
(I am glad to have a conversation in English.)

**Comment by a-know** [comment]
@Sabazo , thank you again for your feedback!
The specification of gradation in Pixela has not been published, but the color scheme is changed in 5 steps relative to the data in the display range. At this time, also consider outliers (such as extremely large values).
However, when I checked based on this issue, it turned out that there is a problem that gradation does not occur if the data in the display range consists of only small values.
I've fixed it a while ago, so check it out, please?

I am very happy about the valuable feedback. Thank you in advance for Pixela!

---
(In Japanese)

@Sabazo さん、改めて、今回のフィードバックありがとうございました！
Pixelaでのグラデーションの仕様は公開してはいないのですが、表示範囲内のデータに対して5段階で相対的に配色を変えるようにしています。この際、外れ値（極端に大きい値など）の考慮もおこなっています。
ただ、今回のご指摘をもとに確認してみたところ、表示範囲内のデータが小さな値のみで構成される場合にグラデーションにならない問題があることがわかりました。
さきほど修正してみましたので、確認してみてください！

貴重なフィードバック、大変うれしいです。今後もPixelaをよろしくお願いします！

**Comment by Sabazo** [comment]
I confirmed that the gradation is displayed. GJ!

グラデーション表示されることを確認しました。
ありがとうございます!
